#standardized way of saving the complexity measures
library(ECoL)

#input-scheme. Simply input dataset name after '_'
overlap_ <- overlapping(bugbinary~., data, measures= "all")
neighbor_ <- neighborhood(bugbinary~., data, measures= "all")
lin_ <- linearity(bugbinary~., data, measures= "all")
dim_ <- dimensionality(bugbinary~., data, measures= "all")
bal_ <- balance(bugbinary~., data, measures= "all")
net_ <- network(bugbinary~., data, measures= "all")
corr_ <- correlation(bugbinary~., data, measures= "all")
smooth_ <- smoothness(bugbinary~., data, measures= "all")


overlap_camel16 <- overlapping(bugbinary~., data, measures= "all")
neighbor_camel16 <- neighborhood(bugbinary~., data, measures= "all")
lin_camel16 <- linearity(bugbinary~., data, measures= "all")
dim_camel16 <- dimensionality(bugbinary~., data, measures= "all")
bal_camel16 <- balance(bugbinary~., data, measures= "all")
net_camel16 <- network(bugbinary~., data, measures= "all")
corr_camel16 <- correlation(bugbinary~., data, measures= "all")
smooth_camel16 <- smoothness(bugbinary~., data, measures= "all")

overlap_ant13 <- overlapping(bugbinary~., data, measures= "all")
neighbor_ant13 <- neighborhood(bugbinary~., data, measures= "all")
lin_ant13 <- linearity(bugbinary~., data, measures= "all")
dim_ant13 <- dimensionality(bugbinary~., data, measures= "all")
bal_ant13 <- balance(bugbinary~., data, measures= "all")
net_ant13 <- network(bugbinary~., data, measures= "all")
corr_ant13 <- correlation(bugbinary~., data, measures= "all")
smooth_ant13 <- smoothness(bugbinary~., data, measures= "all")

overlap_camel10 <- overlapping(bugbinary~., data, measures= "all")
neighbor_camel10 <- neighborhood(bugbinary~., data, measures= "all")
lin_camel10 <- linearity(bugbinary~., data, measures= "all")
dim_camel10 <- dimensionality(bugbinary~., data, measures= "all")
bal_camel10 <- balance(bugbinary~., data, measures= "all")
net_camel10 <- network(bugbinary~., data, measures= "all")
corr_camel10 <- correlation(bugbinary~., data, measures= "all")
smooth_camel10 <- smoothness(bugbinary~., data, measures= "all")

overlap_ckjm18 <- overlapping(bugbinary~., data, measures= "all")
neighbor_ckjm18 <- neighborhood(bugbinary~., data, measures= "all")
lin_ckjm18 <- linearity(bugbinary~., data, measures= "all")
dim_ckjm18 <- dimensionality(bugbinary~., data, measures= "all")
bal_ckjm18 <- balance(bugbinary~., data, measures= "all")
net_ckjm18 <- network(bugbinary~., data, measures= "all")
corr_ckjm18 <- correlation(bugbinary~., data, measures= "all")
smooth_ckjm18 <- smoothness(bugbinary~., data, measures= "all")

overlap_forrest06 <- overlapping(bugbinary~., data, measures= "all")
neighbor_forrest06 <- neighborhood(bugbinary~., data, measures= "all")
lin_forrest06 <- linearity(bugbinary~., data, measures= "all")
dim_forrest06 <- dimensionality(bugbinary~., data, measures= "all")
bal_forrest06 <- balance(bugbinary~., data, measures= "all")
net_forrest06 <- network(bugbinary~., data, measures= "all")
corr_forrest06 <- correlation(bugbinary~., data, measures= "all")
smooth_forrest06 <- smoothness(bugbinary~., data, measures= "all")

overlap_forrest07 <- overlapping(bugbinary~., data, measures= "all")
neighbor_forrest07 <- neighborhood(bugbinary~., data, measures= "all")
lin_forrest07 <- linearity(bugbinary~., data, measures= "all")
dim_forrest07 <- dimensionality(bugbinary~., data, measures= "all")
bal_forrest07 <- balance(bugbinary~., data, measures= "all")
net_forrest07 <- network(bugbinary~., data, measures= "all")
corr_forrest07 <- correlation(bugbinary~., data, measures= "all")
smooth_forrest07 <- smoothness(bugbinary~., data, measures= "all")

overlap_ivy14 <- overlapping(bugbinary~., data, measures= "all")
neighbor_ivy14 <- neighborhood(bugbinary~., data, measures= "all")
lin_ivy14 <- linearity(bugbinary~., data, measures= "all")
dim_ivy14 <- dimensionality(bugbinary~., data, measures= "all")
bal_ivy14 <- balance(bugbinary~., data, measures= "all")
net_ivy14 <- network(bugbinary~., data, measures= "all")
corr_ivy14 <- correlation(bugbinary~., data, measures= "all")
smooth_ivy14 <- smoothness(bugbinary~., data, measures= "all")

overlap_jedit32 <- overlapping(bugbinary~., data, measures= "all")
neighbor_jedit32 <- neighborhood(bugbinary~., data, measures= "all")
lin_jedit32 <- linearity(bugbinary~., data, measures= "all")
dim_jedit32 <- dimensionality(bugbinary~., data, measures= "all")
bal_jedit32 <- balance(bugbinary~., data, measures= "all")
net_jedit32 <- network(bugbinary~., data, measures= "all")
corr_jedit32 <- correlation(bugbinary~., data, measures= "all")
smooth_jedit32 <- smoothness(bugbinary~., data, measures= "all")

overlap_log4j12 <- overlapping(bugbinary~., data, measures= "all")
neighbor_log4j12 <- neighborhood(bugbinary~., data, measures= "all")
lin_log4j12 <- linearity(bugbinary~., data, measures= "all")
dim_log4j12 <- dimensionality(bugbinary~., data, measures= "all")
bal_log4j12 <- balance(bugbinary~., data, measures= "all")
net_log4j12 <- network(bugbinary~., data, measures= "all")
corr_log4j12 <- correlation(bugbinary~., data, measures= "all")
smooth_log4j12 <- smoothness(bugbinary~., data, measures= "all")

overlap_log4j10 <- overlapping(bugbinary~., data, measures= "all")
neighbor_log4j10 <- neighborhood(bugbinary~., data, measures= "all")
lin_log4j10 <- linearity(bugbinary~., data, measures= "all")
dim_log4j10 <- dimensionality(bugbinary~., data, measures= "all")
bal_log4j10 <- balance(bugbinary~., data, measures= "all")
net_log4j10 <- network(bugbinary~., data, measures= "all")
corr_log4j10 <- correlation(bugbinary~., data, measures= "all")
smooth_log4j10 <- smoothness(bugbinary~., data, measures= "all")

overlap_log4j11 <- overlapping(bugbinary~., data, measures= "all")
neighbor_log4j11 <- neighborhood(bugbinary~., data, measures= "all")
lin_log4j11 <- linearity(bugbinary~., data, measures= "all")
dim_log4j11 <- dimensionality(bugbinary~., data, measures= "all")
bal_log4j11 <- balance(bugbinary~., data, measures= "all")
net_log4j11 <- network(bugbinary~., data, measures= "all")
corr_log4j11 <- correlation(bugbinary~., data, measures= "all")
smooth_log4j11 <- smoothness(bugbinary~., data, measures= "all")

overlap_lucene20 <- overlapping(bugbinary~., data, measures= "all")
neighbor_lucene20 <- neighborhood(bugbinary~., data, measures= "all")
lin_lucene20 <- linearity(bugbinary~., data, measures= "all")
dim_lucene20 <- dimensionality(bugbinary~., data, measures= "all")
bal_lucene20 <- balance(bugbinary~., data, measures= "all")
net_lucene20 <- network(bugbinary~., data, measures= "all")
corr_lucene20 <- correlation(bugbinary~., data, measures= "all")
smooth_lucene20 <- smoothness(bugbinary~., data, measures= "all")

overlap_lucene22 <- overlapping(bugbinary~., data, measures= "all")
neighbor_lucene22 <- neighborhood(bugbinary~., data, measures= "all")
lin_lucene22 <- linearity(bugbinary~., data, measures= "all")
dim_lucene22 <- dimensionality(bugbinary~., data, measures= "all")
bal_lucene22 <- balance(bugbinary~., data, measures= "all")
net_lucene22 <- network(bugbinary~., data, measures= "all")
corr_lucene22 <- correlation(bugbinary~., data, measures= "all")
smooth_lucene22 <- smoothness(bugbinary~., data, measures= "all")

overlap_lucene24 <- overlapping(bugbinary~., data, measures= "all")
neighbor_lucene24 <- neighborhood(bugbinary~., data, measures= "all")
lin_lucene24 <- linearity(bugbinary~., data, measures= "all")
dim_lucene24 <- dimensionality(bugbinary~., data, measures= "all")
bal_lucene24 <- balance(bugbinary~., data, measures= "all")
net_lucene24 <- network(bugbinary~., data, measures= "all")
corr_lucene24 <- correlation(bugbinary~., data, measures= "all")
smooth_lucene24 <- smoothness(bugbinary~., data, measures= "all")

overlap_pbeans1 <- overlapping(bugbinary~., data, measures= "all")
neighbor_pbeans1 <- neighborhood(bugbinary~., data, measures= "all")
lin_pbeans1 <- linearity(bugbinary~., data, measures= "all")
dim_pbeans1 <- dimensionality(bugbinary~., data, measures= "all")
bal_pbeans1 <- balance(bugbinary~., data, measures= "all")
net_pbeans1 <- network(bugbinary~., data, measures= "all")
corr_pbeans1 <- correlation(bugbinary~., data, measures= "all")
smooth_pbeans1 <- smoothness(bugbinary~., data, measures= "all")

overlap_pbeans2 <- overlapping(bugbinary~., data, measures= "all")
neighbor_pbeans2 <- neighborhood(bugbinary~., data, measures= "all")
lin_pbeans2 <- linearity(bugbinary~., data, measures= "all")
dim_pbeans2 <- dimensionality(bugbinary~., data, measures= "all")
bal_pbeans2 <- balance(bugbinary~., data, measures= "all")
net_pbeans2 <- network(bugbinary~., data, measures= "all")
corr_pbeans2 <- correlation(bugbinary~., data, measures= "all")
smooth_pbeans2 <- smoothness(bugbinary~., data, measures= "all")

overlap_poi15 <- overlapping(bugbinary~., data, measures= "all")
neighbor_poi15 <- neighborhood(bugbinary~., data, measures= "all")
lin_poi15 <- linearity(bugbinary~., data, measures= "all")
dim_poi15 <- dimensionality(bugbinary~., data, measures= "all")
bal_poi15 <- balance(bugbinary~., data, measures= "all")
net_poi15 <- network(bugbinary~., data, measures= "all")
corr_poi15 <- correlation(bugbinary~., data, measures= "all")
smooth_poi15 <- smoothness(bugbinary~., data, measures= "all")

overlap_poi20 <- overlapping(bugbinary~., data, measures= "all")
neighbor_poi20 <- neighborhood(bugbinary~., data, measures= "all")
lin_poi20 <- linearity(bugbinary~., data, measures= "all")
dim_poi20 <- dimensionality(bugbinary~., data, measures= "all")
bal_poi20 <- balance(bugbinary~., data, measures= "all")
net_poi20 <- network(bugbinary~., data, measures= "all")
corr_poi20 <- correlation(bugbinary~., data, measures= "all")
smooth_poi20 <- smoothness(bugbinary~., data, measures= "all")

overlap_poi25 <- overlapping(bugbinary~., data, measures= "all")
neighbor_poi25 <- neighborhood(bugbinary~., data, measures= "all")
lin_poi25 <- linearity(bugbinary~., data, measures= "all")
dim_poi25 <- dimensionality(bugbinary~., data, measures= "all")
bal_poi25 <- balance(bugbinary~., data, measures= "all")
net_poi25 <- network(bugbinary~., data, measures= "all")
corr_poi25 <- correlation(bugbinary~., data, measures= "all")
smooth_poi25 <- smoothness(bugbinary~., data, measures= "all")

overlap_poi30 <- overlapping(bugbinary~., data, measures= "all")
neighbor_poi30 <- neighborhood(bugbinary~., data, measures= "all")
lin_poi30 <- linearity(bugbinary~., data, measures= "all")
dim_poi30 <- dimensionality(bugbinary~., data, measures= "all")
bal_poi30 <- balance(bugbinary~., data, measures= "all")
net_poi30 <- network(bugbinary~., data, measures= "all")
corr_poi30 <- correlation(bugbinary~., data, measures= "all")
smooth_poi30 <- smoothness(bugbinary~., data, measures= "all")

overlap_synapse10 <- overlapping(bugbinary~., data, measures= "all")
neighbor_synapse10 <- neighborhood(bugbinary~., data, measures= "all")
lin_synapse10 <- linearity(bugbinary~., data, measures= "all")
dim_synapse10 <- dimensionality(bugbinary~., data, measures= "all")
bal_synapse10 <- balance(bugbinary~., data, measures= "all")
net_synapse10 <- network(bugbinary~., data, measures= "all")
corr_synapse10 <- correlation(bugbinary~., data, measures= "all")
smooth_synapse10 <- smoothness(bugbinary~., data, measures= "all")

overlap_synapse11 <- overlapping(bugbinary~., data, measures= "all")
neighbor_synapse11 <- neighborhood(bugbinary~., data, measures= "all")
lin_synapse11 <- linearity(bugbinary~., data, measures= "all")
dim_synapse11 <- dimensionality(bugbinary~., data, measures= "all")
bal_synapse11 <- balance(bugbinary~., data, measures= "all")
net_synapse11 <- network(bugbinary~., data, measures= "all")
corr_synapse11 <- correlation(bugbinary~., data, measures= "all")
smooth_synapse11 <- smoothness(bugbinary~., data, measures= "all")

overlap_synapse12 <- overlapping(bugbinary~., data, measures= "all")
neighbor_synapse12 <- neighborhood(bugbinary~., data, measures= "all")
lin_synapse12 <- linearity(bugbinary~., data, measures= "all")
dim_synapse12 <- dimensionality(bugbinary~., data, measures= "all")
bal_synapse12 <- balance(bugbinary~., data, measures= "all")
net_synapse12 <- network(bugbinary~., data, measures= "all")
corr_synapse12 <- correlation(bugbinary~., data, measures= "all")
smooth_synapse12 <- smoothness(bugbinary~., data, measures= "all")

overlap_velocity14 <- overlapping(bugbinary~., data, measures= "all")
neighbor_velocity14 <- neighborhood(bugbinary~., data, measures= "all")
lin_velocity14 <- linearity(bugbinary~., data, measures= "all")
dim_velocity14 <- dimensionality(bugbinary~., data, measures= "all")
bal_velocity14 <- balance(bugbinary~., data, measures= "all")
net_velocity14 <- network(bugbinary~., data, measures= "all")
corr_velocity14 <- correlation(bugbinary~., data, measures= "all")
smooth_velocity14 <- smoothness(bugbinary~., data, measures= "all")

overlap_velocity15 <- overlapping(bugbinary~., data, measures= "all")
neighbor_velocity15 <- neighborhood(bugbinary~., data, measures= "all")
lin_velocity15 <- linearity(bugbinary~., data, measures= "all")
dim_velocity15 <- dimensionality(bugbinary~., data, measures= "all")
bal_velocity15 <- balance(bugbinary~., data, measures= "all")
net_velocity15 <- network(bugbinary~., data, measures= "all")
corr_velocity15 <- correlation(bugbinary~., data, measures= "all")
smooth_velocity15 <- smoothness(bugbinary~., data, measures= "all")

overlap_velocity16 <- overlapping(bugbinary~., data, measures= "all")
neighbor_velocity16 <- neighborhood(bugbinary~., data, measures= "all")
lin_velocity16 <- linearity(bugbinary~., data, measures= "all")
dim_velocity16 <- dimensionality(bugbinary~., data, measures= "all")
bal_velocity16 <- balance(bugbinary~., data, measures= "all")
net_velocity16 <- network(bugbinary~., data, measures= "all")
corr_velocity16 <- correlation(bugbinary~., data, measures= "all")
smooth_velocity16 <- smoothness(bugbinary~., data, measures= "all")

overlap_xalan24 <- overlapping(bugbinary~., data, measures= "all")
neighbor_xalan24 <- neighborhood(bugbinary~., data, measures= "all")
lin_xalan24 <- linearity(bugbinary~., data, measures= "all")
dim_xalan24 <- dimensionality(bugbinary~., data, measures= "all")
bal_xalan24 <- balance(bugbinary~., data, measures= "all")
net_xalan24 <- network(bugbinary~., data, measures= "all")
corr_xalan24 <- correlation(bugbinary~., data, measures= "all")
smooth_xalan24 <- smoothness(bugbinary~., data, measures= "all")

overlap_xalan25 <- overlapping(bugbinary~., data, measures= "all")
neighbor_xalan25 <- neighborhood(bugbinary~., data, measures= "all")
lin_xalan25 <- linearity(bugbinary~., data, measures= "all")
dim_xalan25 <- dimensionality(bugbinary~., data, measures= "all")
bal_xalan25 <- balance(bugbinary~., data, measures= "all")
net_xalan25 <- network(bugbinary~., data, measures= "all")
corr_xalan25 <- correlation(bugbinary~., data, measures= "all")
smooth_xalan25 <- smoothness(bugbinary~., data, measures= "all")

overlap_xalan26 <- overlapping(bugbinary~., data, measures= "all")
neighbor_xalan26 <- neighborhood(bugbinary~., data, measures= "all")
lin_xalan26 <- linearity(bugbinary~., data, measures= "all")
dim_xalan26 <- dimensionality(bugbinary~., data, measures= "all")
bal_xalan26 <- balance(bugbinary~., data, measures= "all")
net_xalan26 <- network(bugbinary~., data, measures= "all")
corr_xalan26 <- correlation(bugbinary~., data, measures= "all")
smooth_xalan26 <- smoothness(bugbinary~., data, measures= "all")

overlap_xalan27 <- overlapping(bugbinary~., data, measures= "all")
neighbor_xalan27 <- neighborhood(bugbinary~., data, measures= "all")
lin_xalan27 <- linearity(bugbinary~., data, measures= "all")
dim_xalan27 <- dimensionality(bugbinary~., data, measures= "all")
bal_xalan27 <- balance(bugbinary~., data, measures= "all")
net_xalan27 <- network(bugbinary~., data, measures= "all")
corr_xalan27 <- correlation(bugbinary~., data, measures= "all")
smooth_xalan27 <- smoothness(bugbinary~., data, measures= "all")

overlap_xerces12 <- overlapping(bugbinary~., data, measures= "all")
neighbor_xerces12 <- neighborhood(bugbinary~., data, measures= "all")
lin_xerces12 <- linearity(bugbinary~., data, measures= "all")
dim_xerces12 <- dimensionality(bugbinary~., data, measures= "all")
bal_xerces12 <- balance(bugbinary~., data, measures= "all")
net_xerces12 <- network(bugbinary~., data, measures= "all")
corr_xerces12 <- correlation(bugbinary~., data, measures= "all")
smooth_xerces12 <- smoothness(bugbinary~., data, measures= "all")

overlap_xerces13 <- overlapping(bugbinary~., data, measures= "all")
neighbor_xerces13 <- neighborhood(bugbinary~., data, measures= "all")
lin_xerces13 <- linearity(bugbinary~., data, measures= "all")
dim_xerces13 <- dimensionality(bugbinary~., data, measures= "all")
bal_xerces13 <- balance(bugbinary~., data, measures= "all")
net_xerces13 <- network(bugbinary~., data, measures= "all")
corr_xerces13 <- correlation(bugbinary~., data, measures= "all")
smooth_xerces13 <- smoothness(bugbinary~., data, measures= "all")

overlap_xerces20 <- overlapping(bugbinary~., data, measures= "all")
neighbor_xerces20 <- neighborhood(bugbinary~., data, measures= "all")
lin_xerces20 <- linearity(bugbinary~., data, measures= "all")
dim_xerces20 <- dimensionality(bugbinary~., data, measures= "all")
bal_xerces20 <- balance(bugbinary~., data, measures= "all")
net_xerces20 <- network(bugbinary~., data, measures= "all")
corr_xerces20 <- correlation(bugbinary~., data, measures= "all")
smooth_xerces20 <- smoothness(bugbinary~., data, measures= "all")

overlap_camel16 <- overlapping(bugbinary~., data, measures= "all")
neighbor_camel16 <- neighborhood(bugbinary~., data, measures= "all")
lin_camel16 <- linearity(bugbinary~., data, measures= "all")
dim_camel16 <- dimensionality(bugbinary~., data, measures= "all")
bal_camel16 <- balance(bugbinary~., data, measures= "all")
net_camel16 <- network(bugbinary~., data, measures= "all")
corr_camel16 <- correlation(bugbinary~., data, measures= "all")
smooth_camel16 <- smoothness(bugbinary~., data, measures= "all")

overlap_forrest08 <- overlapping(bugbinary~., data, measures= "all")
neighbor_forrest08 <- neighborhood(bugbinary~., data, measures= "all")
lin_forrest08 <- linearity(bugbinary~., data, measures= "all")
dim_forrest08 <- dimensionality(bugbinary~., data, measures= "all")
bal_forrest08 <- balance(bugbinary~., data, measures= "all")
net_forrest08 <- network(bugbinary~., data, measures= "all")
corr_forrest08 <- correlation(bugbinary~., data, measures= "all")
smooth_forrest08 <- smoothness(bugbinary~., data, measures= "all")

overlap_ivy20 <- overlapping(bugbinary~., data, measures= "all")
neighbor_ivy20 <- neighborhood(bugbinary~., data, measures= "all")
lin_ivy20 <- linearity(bugbinary~., data, measures= "all")
dim_ivy20 <- dimensionality(bugbinary~., data, measures= "all")
bal_ivy20 <- balance(bugbinary~., data, measures= "all")
net_ivy20 <- network(bugbinary~., data, measures= "all")
corr_ivy20 <- correlation(bugbinary~., data, measures= "all")
smooth_ivy20 <- smoothness(bugbinary~., data, measures= "all")

overlap_jedit43 <- overlapping(bugbinary~., data, measures= "all")
neighbor_jedit43 <- neighborhood(bugbinary~., data, measures= "all")
lin_jedit43 <- linearity(bugbinary~., data, measures= "all")
dim_jedit43 <- dimensionality(bugbinary~., data, measures= "all")
bal_jedit43 <- balance(bugbinary~., data, measures= "all")
net_jedit43 <- network(bugbinary~., data, measures= "all")
corr_jedit43 <- correlation(bugbinary~., data, measures= "all")
smooth_jedit43 <- smoothness(bugbinary~., data, measures= "all")

overlap_log4k12 <- overlapping(bugbinary~., data, measures= "all")
neighbor_log4k12 <- neighborhood(bugbinary~., data, measures= "all")
lin_log4k12 <- linearity(bugbinary~., data, measures= "all")
dim_log4k12 <- dimensionality(bugbinary~., data, measures= "all")
bal_log4k12 <- balance(bugbinary~., data, measures= "all")
net_log4k12 <- network(bugbinary~., data, measures= "all")
corr_log4k12 <- correlation(bugbinary~., data, measures= "all")
smooth_log4k12 <- smoothness(bugbinary~., data, measures= "all")

overlap_lucene24 <- overlapping(bugbinary~., data, measures= "all")
neighbor_lucene24 <- neighborhood(bugbinary~., data, measures= "all")
lin_lucene24 <- linearity(bugbinary~., data, measures= "all")
dim_lucene24 <- dimensionality(bugbinary~., data, measures= "all")
bal_lucene24 <- balance(bugbinary~., data, measures= "all")
net_lucene24 <- network(bugbinary~., data, measures= "all")
corr_lucene24 <- correlation(bugbinary~., data, measures= "all")
smooth_lucene24 <- smoothness(bugbinary~., data, measures= "all")

overlap_pbeans2 <- overlapping(bugbinary~., data, measures= "all")
neighbor_pbeans2 <- neighborhood(bugbinary~., data, measures= "all")
lin_pbeans2 <- linearity(bugbinary~., data, measures= "all")
dim_pbeans2 <- dimensionality(bugbinary~., data, measures= "all")
bal_pbeans2 <- balance(bugbinary~., data, measures= "all")
net_pbeans2 <- network(bugbinary~., data, measures= "all")
corr_pbeans2 <- correlation(bugbinary~., data, measures= "all")
smooth_pbeans2 <- smoothness(bugbinary~., data, measures= "all")