#standardized way of saving the complexity measures
library(ECoL)

#input-scheme. Simply input dataset name after '_'
overlap_ <- overlapping(bugbinary~., data, measures= "all")
neighbor_ <- neighborhood(bugbinary~., data, measures= "all")
lin_ <- linearity(bugbinary~., data, measures= "all")
dim_ <- dimensionality(bugbinary~., data, measures= "all")
bal_ <- balance(bugbinary~., data, measures= "all")
net_ <- network(bugbinary~., data, measures= "all")
corr_ <- correlation(bugbinary~., data, measures= "all")
smooth_ <- smoothness(bugbinary~., data, measures= "all")

overlap_ant13 <- overlapping(bugbinary~., data, measures= "all")
neighbor_ant13 <- neighborhood(bugbinary~., data, measures= "all")
lin_ant13 <- linearity(bugbinary~., data, measures= "all")
dim_ant13 <- dimensionality(bugbinary~., data, measures= "all")
bal_ant13 <- balance(bugbinary~., data, measures= "all")
net_ant13 <- network(bugbinary~., data, measures= "all")
corr_ant13 <- correlation(bugbinary~., data, measures= "all")
smooth_ant13 <- smoothness(bugbinary~., data, measures= "all")

overlap_camel10 <- overlapping(bugbinary~., data, measures= "all")
neighbor_camel10 <- neighborhood(bugbinary~., data, measures= "all")
lin_camel10 <- linearity(bugbinary~., data, measures= "all")
dim_camel10 <- dimensionality(bugbinary~., data, measures= "all")
bal_camel10 <- balance(bugbinary~., data, measures= "all")
net_camel10 <- network(bugbinary~., data, measures= "all")
corr_camel10 <- correlation(bugbinary~., data, measures= "all")
smooth_camel10 <- smoothness(bugbinary~., data, measures= "all")

overlap_ckjm18 <- overlapping(bugbinary~., data, measures= "all")
neighbor_ckjm18 <- neighborhood(bugbinary~., data, measures= "all")
lin_ckjm18 <- linearity(bugbinary~., data, measures= "all")
dim_ckjm18 <- dimensionality(bugbinary~., data, measures= "all")
bal_ckjm18 <- balance(bugbinary~., data, measures= "all")
net_ckjm18 <- network(bugbinary~., data, measures= "all")
corr_ckjm18 <- correlation(bugbinary~., data, measures= "all")
smooth_ckjm18 <- smoothness(bugbinary~., data, measures= "all")

overlap_forrest06 <- overlapping(bugbinary~., data, measures= "all")
neighbor_forrest06 <- neighborhood(bugbinary~., data, measures= "all")
lin_forrest06 <- linearity(bugbinary~., data, measures= "all")
dim_forrest06 <- dimensionality(bugbinary~., data, measures= "all")
bal_forrest06 <- balance(bugbinary~., data, measures= "all")
net_forrest06 <- network(bugbinary~., data, measures= "all")
corr_forrest06 <- correlation(bugbinary~., data, measures= "all")
smooth_forrest06 <- smoothness(bugbinary~., data, measures= "all")

overlap_forrest07 <- overlapping(bugbinary~., data, measures= "all")
neighbor_forrest07 <- neighborhood(bugbinary~., data, measures= "all")
lin_forrest07 <- linearity(bugbinary~., data, measures= "all")
dim_forrest07 <- dimensionality(bugbinary~., data, measures= "all")
bal_forrest07 <- balance(bugbinary~., data, measures= "all")
net_forrest07 <- network(bugbinary~., data, measures= "all")
corr_forrest07 <- correlation(bugbinary~., data, measures= "all")
smooth_forrest07 <- smoothness(bugbinary~., data, measures= "all")

overlap_ivy14 <- overlapping(bugbinary~., data, measures= "all")
neighbor_ivy14 <- neighborhood(bugbinary~., data, measures= "all")
lin_ivy14 <- linearity(bugbinary~., data, measures= "all")
dim_ivy14 <- dimensionality(bugbinary~., data, measures= "all")
bal_ivy14 <- balance(bugbinary~., data, measures= "all")
net_ivy14 <- network(bugbinary~., data, measures= "all")
corr_ivy14 <- correlation(bugbinary~., data, measures= "all")
smooth_ivy14 <- smoothness(bugbinary~., data, measures= "all")

overlap_jedit32 <- overlapping(bugbinary~., data, measures= "all")
neighbor_jedit32 <- neighborhood(bugbinary~., data, measures= "all")
lin_jedit32 <- linearity(bugbinary~., data, measures= "all")
dim_jedit32 <- dimensionality(bugbinary~., data, measures= "all")
bal_jedit32 <- balance(bugbinary~., data, measures= "all")
net_jedit32 <- network(bugbinary~., data, measures= "all")
corr_jedit32 <- correlation(bugbinary~., data, measures= "all")
smooth_jedit32 <- smoothness(bugbinary~., data, measures= "all")

overlap_log4j12 <- overlapping(bugbinary~., data, measures= "all")
neighbor_log4j12 <- neighborhood(bugbinary~., data, measures= "all")
lin_log4j12 <- linearity(bugbinary~., data, measures= "all")
dim_log4j12 <- dimensionality(bugbinary~., data, measures= "all")
bal_log4j12 <- balance(bugbinary~., data, measures= "all")
net_log4j12 <- network(bugbinary~., data, measures= "all")
corr_log4j12 <- correlation(bugbinary~., data, measures= "all")
smooth_log4j12 <- smoothness(bugbinary~., data, measures= "all")

overlap_log4j10 <- overlapping(bugbinary~., data, measures= "all")
neighbor_log4j10 <- neighborhood(bugbinary~., data, measures= "all")
lin_log4j10 <- linearity(bugbinary~., data, measures= "all")
dim_log4j10 <- dimensionality(bugbinary~., data, measures= "all")
bal_log4j10 <- balance(bugbinary~., data, measures= "all")
net_log4j10 <- network(bugbinary~., data, measures= "all")
corr_log4j10 <- correlation(bugbinary~., data, measures= "all")
smooth_log4j10 <- smoothness(bugbinary~., data, measures= "all")

overlap_log4j11 <- overlapping(bugbinary~., data, measures= "all")
neighbor_log4j11 <- neighborhood(bugbinary~., data, measures= "all")
lin_log4j11 <- linearity(bugbinary~., data, measures= "all")
dim_log4j11 <- dimensionality(bugbinary~., data, measures= "all")
bal_log4j11 <- balance(bugbinary~., data, measures= "all")
net_log4j11 <- network(bugbinary~., data, measures= "all")
corr_log4j11 <- correlation(bugbinary~., data, measures= "all")
smooth_log4j11 <- smoothness(bugbinary~., data, measures= "all")

overlap_lucene20 <- overlapping(bugbinary~., data, measures= "all")
neighbor_lucene20 <- neighborhood(bugbinary~., data, measures= "all")
lin_lucene20 <- linearity(bugbinary~., data, measures= "all")
dim_lucene20 <- dimensionality(bugbinary~., data, measures= "all")
bal_lucene20 <- balance(bugbinary~., data, measures= "all")
net_lucene20 <- network(bugbinary~., data, measures= "all")
corr_lucene20 <- correlation(bugbinary~., data, measures= "all")
smooth_lucene20 <- smoothness(bugbinary~., data, measures= "all")

overlap_lucene22 <- overlapping(bugbinary~., data, measures= "all")
neighbor_lucene22 <- neighborhood(bugbinary~., data, measures= "all")
lin_lucene22 <- linearity(bugbinary~., data, measures= "all")
dim_lucene22 <- dimensionality(bugbinary~., data, measures= "all")
bal_lucene22 <- balance(bugbinary~., data, measures= "all")
net_lucene22 <- network(bugbinary~., data, measures= "all")
corr_lucene22 <- correlation(bugbinary~., data, measures= "all")
smooth_lucene22 <- smoothness(bugbinary~., data, measures= "all")

overlap_lucene24 <- overlapping(bugbinary~., data, measures= "all")
neighbor_lucene24 <- neighborhood(bugbinary~., data, measures= "all")
lin_lucene24 <- linearity(bugbinary~., data, measures= "all")
dim_lucene24 <- dimensionality(bugbinary~., data, measures= "all")
bal_lucene24 <- balance(bugbinary~., data, measures= "all")
net_lucene24 <- network(bugbinary~., data, measures= "all")
corr_lucene24 <- correlation(bugbinary~., data, measures= "all")
smooth_lucene24 <- smoothness(bugbinary~., data, measures= "all")

overlap_pbeans1 <- overlapping(bugbinary~., data, measures= "all")
neighbor_pbeans1 <- neighborhood(bugbinary~., data, measures= "all")
lin_pbeans1 <- linearity(bugbinary~., data, measures= "all")
dim_pbeans1 <- dimensionality(bugbinary~., data, measures= "all")
bal_pbeans1 <- balance(bugbinary~., data, measures= "all")
net_pbeans1 <- network(bugbinary~., data, measures= "all")
corr_pbeans1 <- correlation(bugbinary~., data, measures= "all")
smooth_pbeans1 <- smoothness(bugbinary~., data, measures= "all")

overlap_pbeans2 <- overlapping(bugbinary~., data, measures= "all")
neighbor_pbeans2 <- neighborhood(bugbinary~., data, measures= "all")
lin_pbeans2 <- linearity(bugbinary~., data, measures= "all")
dim_pbeans2 <- dimensionality(bugbinary~., data, measures= "all")
bal_pbeans2 <- balance(bugbinary~., data, measures= "all")
net_pbeans2 <- network(bugbinary~., data, measures= "all")
corr_pbeans2 <- correlation(bugbinary~., data, measures= "all")
smooth_pbeans2 <- smoothness(bugbinary~., data, measures= "all")

overlap_poi15 <- overlapping(bugbinary~., data, measures= "all")
neighbor_poi15 <- neighborhood(bugbinary~., data, measures= "all")
lin_poi15 <- linearity(bugbinary~., data, measures= "all")
dim_poi15 <- dimensionality(bugbinary~., data, measures= "all")
bal_poi15 <- balance(bugbinary~., data, measures= "all")
net_poi15 <- network(bugbinary~., data, measures= "all")
corr_poi15 <- correlation(bugbinary~., data, measures= "all")
smooth_poi15 <- smoothness(bugbinary~., data, measures= "all")

overlap_poi20 <- overlapping(bugbinary~., data, measures= "all")
neighbor_poi20 <- neighborhood(bugbinary~., data, measures= "all")
lin_poi20 <- linearity(bugbinary~., data, measures= "all")
dim_poi20 <- dimensionality(bugbinary~., data, measures= "all")
bal_poi20 <- balance(bugbinary~., data, measures= "all")
net_poi20 <- network(bugbinary~., data, measures= "all")
corr_poi20 <- correlation(bugbinary~., data, measures= "all")
smooth_poi20 <- smoothness(bugbinary~., data, measures= "all")

overlap_poi25 <- overlapping(bugbinary~., data, measures= "all")
neighbor_poi25 <- neighborhood(bugbinary~., data, measures= "all")
lin_poi25 <- linearity(bugbinary~., data, measures= "all")
dim_poi25 <- dimensionality(bugbinary~., data, measures= "all")
bal_poi25 <- balance(bugbinary~., data, measures= "all")
net_poi25 <- network(bugbinary~., data, measures= "all")
corr_poi25 <- correlation(bugbinary~., data, measures= "all")
smooth_poi25 <- smoothness(bugbinary~., data, measures= "all")

overlap_poi30 <- overlapping(bugbinary~., data, measures= "all")
neighbor_poi30 <- neighborhood(bugbinary~., data, measures= "all")
lin_poi30 <- linearity(bugbinary~., data, measures= "all")
dim_poi30 <- dimensionality(bugbinary~., data, measures= "all")
bal_poi30 <- balance(bugbinary~., data, measures= "all")
net_poi30 <- network(bugbinary~., data, measures= "all")
corr_poi30 <- correlation(bugbinary~., data, measures= "all")
smooth_poi30 <- smoothness(bugbinary~., data, measures= "all")

overlap_synapse10 <- overlapping(bugbinary~., data, measures= "all")
neighbor_synapse10 <- neighborhood(bugbinary~., data, measures= "all")
lin_synapse10 <- linearity(bugbinary~., data, measures= "all")
dim_synapse10 <- dimensionality(bugbinary~., data, measures= "all")
bal_synapse10 <- balance(bugbinary~., data, measures= "all")
net_synapse10 <- network(bugbinary~., data, measures= "all")
corr_synapse10 <- correlation(bugbinary~., data, measures= "all")
smooth_synapse10 <- smoothness(bugbinary~., data, measures= "all")

overlap_synapse11 <- overlapping(bugbinary~., data, measures= "all")
neighbor_synapse11 <- neighborhood(bugbinary~., data, measures= "all")
lin_synapse11 <- linearity(bugbinary~., data, measures= "all")
dim_synapse11 <- dimensionality(bugbinary~., data, measures= "all")
bal_synapse11 <- balance(bugbinary~., data, measures= "all")
net_synapse11 <- network(bugbinary~., data, measures= "all")
corr_synapse11 <- correlation(bugbinary~., data, measures= "all")
smooth_synapse11 <- smoothness(bugbinary~., data, measures= "all")